// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/equipos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todos los equipos donde el usuario es propietario o miembro.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipos"
                ],
                "summary": "Listar equipos del usuario autenticado",
                "responses": {
                    "200": {
                        "description": "Lista de equipos obtenida exitosamente",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Equipo"
                            }
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un equipo asignando automáticamente al usuario autenticado (vía JWT) como propietario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipos"
                ],
                "summary": "Crear un nuevo equipo de trabajo",
                "parameters": [
                    {
                        "description": "Datos para crear el equipo",
                        "name": "equipo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Equipo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Equipo creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Equipo"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipos/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna los datos de un equipo específico, incluyendo miembros y tareas asociadas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipos"
                ],
                "summary": "Obtener un equipo por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Datos del equipo obtenidos exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Equipo"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Acceso denegado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina permanentemente un equipo. Solo el propietario (OwnerID) puede realizar esta acción.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipos"
                ],
                "summary": "Eliminar un equipo por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del equipo a eliminar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Equipo eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Permisos insuficientes",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipos/{id}/miembros": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna la lista de usuarios que son miembros de un equipo específico, incluyendo su rol y datos básicos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Miembros"
                ],
                "summary": "Obtener miembros de un equipo",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de miembros obtenida exitosamente",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Miembro"
                            }
                        }
                    },
                    "400": {
                        "description": "ID de equipo inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un registro de miembro y lo asocia a un equipo existente. Solo el propietario del equipo puede realizar esta acción.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Miembros"
                ],
                "summary": "Agregar un miembro a un equipo",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del miembro a agregar",
                        "name": "miembro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Miembro"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Miembro agregado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Miembro"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID incorrecto",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipos/{id}/miembros/{usuarioId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remueve permanentemente la relación de un usuario con un equipo. Solo el propietario del equipo puede realizar esta acción.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Miembros"
                ],
                "summary": "Eliminar un miembro de un equipo",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 5,
                        "description": "ID del usuario a eliminar",
                        "name": "usuarioId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Miembro eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "IDs inválidos o formato incorrecto",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Permisos insuficientes",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Miembro no encontrado en este equipo",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipos/{id}/tareas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todas las tareas asociadas a un equipo específico, incluyendo el nombre del usuario asignado (si existe).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Listar tareas de un equipo",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de tareas obtenida exitosamente",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TareaConAsignadoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "ID de equipo inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una tarea dentro de un equipo específico y la inicializa en estado \"backlog\". Opcionalmente se puede asignar a un miembro.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Crear una nueva tarea en un equipo",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "ID del equipo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de la tarea a crear",
                        "name": "datos",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Tarea"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tarea creada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Tarea"
                        }
                    },
                    "400": {
                        "description": "ID de equipo inválido o datos incorrectos",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipo no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica al usuario con email y contraseña. Retorna un token JWT válido por 24 horas para usar en endpoints protegidos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Iniciar sesión de usuario",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login exitoso",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado o contraseña incorrecta",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna los datos públicos del usuario que inició sesión, obtenidos desde el token JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Obtener perfil del usuario autenticado",
                "responses": {
                    "200": {
                        "description": "Perfil obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite modificar el nombre y/o contraseña del usuario logueado. Solo los campos enviados serán actualizados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Actualizar perfil del usuario autenticado",
                "parameters": [
                    {
                        "description": "Campos a actualizar",
                        "name": "datos",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o error al encriptar",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registro": {
            "post": {
                "description": "Crea una cuenta de usuario con email y contraseña. La contraseña se encripta automáticamente con bcrypt antes de guardar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registrar un nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos de registro",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario registrado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Usuario"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o error al encriptar contraseña",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tareas/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna los detalles completos de una tarea específica identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Obtener una tarea por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 42,
                        "description": "ID de la tarea",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tarea obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Tarea"
                        }
                    },
                    "400": {
                        "description": "ID de tarea inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tarea no encontrada",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite modificar los campos de una tarea (título, descripción, asignado, etc.). Solo campos enviados serán actualizados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Actualizar una tarea existente",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 42,
                        "description": "ID de la tarea",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a actualizar",
                        "name": "datos",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Tarea"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tarea actualizada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.Tarea"
                        }
                    },
                    "400": {
                        "description": "ID inválido o datos incorrectos",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tarea no encontrada",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina permanentemente una tarea del sistema. Esta acción no se puede deshacer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Eliminar una tarea",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 42,
                        "description": "ID de la tarea a eliminar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tarea eliminada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "ID de tarea inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Permisos insuficientes para eliminar",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tarea no encontrada",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tareas/{id}/estado": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza únicamente el campo ` + "`" + `estado` + "`" + ` de una tarea. Valores permitidos: \"backlog\", \"pendiente\", \"en_progreso\", \"completada\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tareas"
                ],
                "summary": "Cambiar el estado de una tarea",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 42,
                        "description": "ID de la tarea",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo estado de la tarea",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateEstadoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Estado actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido, datos incorrectos o estado no permitido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tarea no encontrada",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/usuarios/buscar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite buscar un usuario existente usando su email. Útil para verificar disponibilidad antes de registrar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Buscar usuario por email",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ana@example.com",
                        "description": "Email del usuario a buscar",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Parámetro email faltante",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autenticado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.Equipo": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "descripcion": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "miembros": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Miembro"
                    }
                },
                "nombre": {
                    "type": "string"
                },
                "ownerid": {
                    "type": "integer"
                },
                "tareas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tarea"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "Datos inválidos"
                },
                "message": {
                    "type": "string",
                    "example": "Campo requerido"
                }
            }
        },
        "models.LoginRequest": {
            "description": "Credenciales requeridas para autenticación",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ana@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MiClave123"
                }
            }
        },
        "models.LoginResponse": {
            "description": "Contiene el token JWT para autenticar requests posteriores",
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operación exitosa"
                }
            }
        },
        "models.Miembro": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "equipo": {
                    "$ref": "#/definitions/models.Equipo"
                },
                "equipoid": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "rol": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "usuario": {
                    "$ref": "#/definitions/models.Usuario"
                },
                "usuarioid": {
                    "type": "integer"
                }
            }
        },
        "models.RegisterRequest": {
            "description": "Información requerida para crear una cuenta",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ana@example.com"
                },
                "nombre": {
                    "type": "string",
                    "example": "Ana López"
                },
                "password": {
                    "type": "string",
                    "example": "MiClave123"
                }
            }
        },
        "models.Tarea": {
            "type": "object",
            "properties": {
                "asignadoid": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "descripcion": {
                    "type": "string"
                },
                "equipoid": {
                    "type": "integer"
                },
                "estado": {
                    "type": "string"
                },
                "fechaLimite": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "prioridad": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.TareaConAsignadoResponse": {
            "description": "Respuesta de tarea que incluye el nombre del miembro asignado (si existe)",
            "type": "object",
            "properties": {
                "asignado_id": {
                    "type": "integer",
                    "example": 5
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-28T10:00:00Z"
                },
                "descripcion": {
                    "type": "string",
                    "example": "Corregir error en autenticación"
                },
                "equipo_id": {
                    "type": "integer",
                    "example": 3
                },
                "estado": {
                    "type": "string",
                    "example": "en_progreso"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombreAsignado": {
                    "type": "string",
                    "example": "Ana López"
                },
                "titulo": {
                    "type": "string",
                    "example": "Fix login bug"
                }
            }
        },
        "models.UpdateEstadoRequest": {
            "description": "Solo contiene el campo estado con valores permitidos",
            "type": "object",
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "backlog",
                        "pendiente",
                        "en_progreso",
                        "completada"
                    ],
                    "example": "en_progreso"
                }
            }
        },
        "models.UpdateProfileRequest": {
            "description": "Campos opcionales para actualizar. Solo los enviados serán modificados.",
            "type": "object",
            "properties": {
                "nombre": {
                    "type": "string",
                    "example": "Ana López Actualizado"
                },
                "password": {
                    "type": "string",
                    "example": "NuevaClave456"
                }
            }
        },
        "models.UserProfileResponse": {
            "description": "Datos visibles del usuario autenticado",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ana@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Ana López"
                }
            }
        },
        "models.Usuario": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "equipos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Equipo"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:7000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Taskly API",
	Description:      "Documentación automática del backend de Taskly",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
